<?php

/**
 * Showcase API
 * PHP version 7.4
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for FHStP Showcase
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 * Extend this class with your controller. You can inject dependencies via class constructor,
 * @see https://github.com/PHP-DI/Slim-Bridge basic example.
 */
namespace OpenAPIServer\Api;

use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;
use Slim\Exception\HttpNotImplementedException;

/**
 * AbstractSourceApi Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
abstract class AbstractSourceApi
{
    /**
     * GET getSourceById
     * Summary: Source by id
     * Notes: Retrieve a source code by its id.
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param int $sourceId The id of the source code to retrieve
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getSourceById(
        ServerRequestInterface $request,
        ResponseInterface $response,
        int $sourceId
    ): ResponseInterface {
        $message = "How about implementing getSourceById as a GET method in OpenAPIServer\Api\SourceApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET getSourcesByExample
     * Summary: Sources by example
     * Notes: Retrieve all source codes of a specific example.
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getSourcesByExample(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $queryParams = $request->getQueryParams();
        $exampleId = (key_exists('exampleId', $queryParams)) ? $queryParams['exampleId'] : null;
        $message = "How about implementing getSourcesByExample as a GET method in OpenAPIServer\Api\SourceApi class?";
        throw new HttpNotImplementedException($request, $message);
    }
}
