<?php

/**
 * Showcase API
 * PHP version 7.4
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for FHSTP Showcase
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 * Extend this class with your controller. You can inject dependencies via class constructor,
 * @see https://github.com/PHP-DI/Slim-Bridge basic example.
 */
namespace OpenAPIServer\Api;

use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;
use Slim\Exception\HttpNotImplementedException;

/**
 * AbstractSourcetypeApi Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
abstract class AbstractSourcetypeApi
{
    /**
     * GET getSourceTypeById
     * Summary: Source type by id
     * Notes: Retrieve a source code type by its id.
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param int $typeId The id of the source code type to retrieve
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getSourceTypeById(
        ServerRequestInterface $request,
        ResponseInterface $response,
        int $typeId
    ): ResponseInterface {
        $message = "How about implementing getSourceTypeById as a GET method in OpenAPIServer\Api\SourcetypeApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET getSourceTypes
     * Summary: All source types
     * Notes: Retrieve all source code types.
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getSourceTypes(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $message = "How about implementing getSourceTypes as a GET method in OpenAPIServer\Api\SourcetypeApi class?";
        throw new HttpNotImplementedException($request, $message);
    }
}
