<?php

/**
 * Showcase API
 * PHP version 7.4
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for FHSTP Showcase
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 * Extend this class with your controller. You can inject dependencies via class constructor,
 * @see https://github.com/PHP-DI/Slim-Bridge basic example.
 */
namespace OpenAPIServer\Api;

use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;
use Slim\Exception\HttpNotImplementedException;

/**
 * AbstractExampleApi Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
abstract class AbstractExampleApi
{
    /**
     * GET getExampleById
     * Summary: Example by id
     * Notes: Retrieve an example by its id.
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param int $exampleId The id of the example to retrieve
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getExampleById(
        ServerRequestInterface $request,
        ResponseInterface $response,
        int $exampleId
    ): ResponseInterface {
        $message = "How about implementing getExampleById as a GET method in OpenAPIServer\Api\ExampleApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET getExamplesBySession
     * Summary: Examples by session
     * Notes: Retrieve all examples of a specific session.
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getExamplesBySession(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $queryParams = $request->getQueryParams();
        $session = (key_exists('session', $queryParams)) ? $queryParams['session'] : null;
        $message = "How about implementing getExamplesBySession as a GET method in OpenAPIServer\Api\ExampleApi class?";
        throw new HttpNotImplementedException($request, $message);
    }
}
