<?php

/**
 * Showcase API
 * PHP version 7.4
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for FHSTP Showcase
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 * Extend this class with your controller. You can inject dependencies via class constructor,
 * @see https://github.com/PHP-DI/Slim-Bridge basic example.
 */
namespace OpenAPIServer\Api;

use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;
use Slim\Exception\HttpNotImplementedException;

/**
 * AbstractSessionApi Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
abstract class AbstractSessionApi
{
    /**
     * GET getSessionById
     * Summary: Session by id
     * Notes: Retrieve a session by its id.
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param int $sessionId The id of the session to retrieve
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getSessionById(
        ServerRequestInterface $request,
        ResponseInterface $response,
        int $sessionId
    ): ResponseInterface {
        $message = "How about implementing getSessionById as a GET method in OpenAPIServer\Api\SessionApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET getSessionsByCourse
     * Summary: Sessions by course
     * Notes: Retrieve all sessions of a specific course.
     * Output-Formats: [application/json]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getSessionsByCourse(
        ServerRequestInterface $request,
        ResponseInterface $response
    ): ResponseInterface {
        $queryParams = $request->getQueryParams();
        $courseId = (key_exists('courseId', $queryParams)) ? $queryParams['courseId'] : null;
        $message = "How about implementing getSessionsByCourse as a GET method in OpenAPIServer\Api\SessionApi class?";
        throw new HttpNotImplementedException($request, $message);
    }
}
