<?php

/**
 * Showcase API
 * PHP version 7.4
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for FHSTP Showcase
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace OpenAPIServer\Api;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Api\DefaultApi;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Api\DefaultApi
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for courseCourseIdGet
     *
     * Course by id.
     *
     * @covers ::courseCourseIdGet
     */
    public function testCourseCourseIdGet()
    {
        $this->markTestIncomplete(
            'Test of "courseCourseIdGet" method has not been implemented yet.'
        );
    }

    /**
     * Test case for courseGet
     *
     * All courses.
     *
     * @covers ::courseGet
     */
    public function testCourseGet()
    {
        $this->markTestIncomplete(
            'Test of "courseGet" method has not been implemented yet.'
        );
    }

    /**
     * Test case for exampleExampleIdGet
     *
     * Example by id.
     *
     * @covers ::exampleExampleIdGet
     */
    public function testExampleExampleIdGet()
    {
        $this->markTestIncomplete(
            'Test of "exampleExampleIdGet" method has not been implemented yet.'
        );
    }

    /**
     * Test case for exampleGet
     *
     * Examples by session.
     *
     * @covers ::exampleGet
     */
    public function testExampleGet()
    {
        $this->markTestIncomplete(
            'Test of "exampleGet" method has not been implemented yet.'
        );
    }

    /**
     * Test case for sessionGet
     *
     * Sessions by course.
     *
     * @covers ::sessionGet
     */
    public function testSessionGet()
    {
        $this->markTestIncomplete(
            'Test of "sessionGet" method has not been implemented yet.'
        );
    }

    /**
     * Test case for sessionSessionIdGet
     *
     * Session by id.
     *
     * @covers ::sessionSessionIdGet
     */
    public function testSessionSessionIdGet()
    {
        $this->markTestIncomplete(
            'Test of "sessionSessionIdGet" method has not been implemented yet.'
        );
    }

    /**
     * Test case for sourceGet
     *
     * Sources by example.
     *
     * @covers ::sourceGet
     */
    public function testSourceGet()
    {
        $this->markTestIncomplete(
            'Test of "sourceGet" method has not been implemented yet.'
        );
    }

    /**
     * Test case for sourceSourceIdGet
     *
     * Source by id.
     *
     * @covers ::sourceSourceIdGet
     */
    public function testSourceSourceIdGet()
    {
        $this->markTestIncomplete(
            'Test of "sourceSourceIdGet" method has not been implemented yet.'
        );
    }

    /**
     * Test case for sourcetypeGet
     *
     * All source types.
     *
     * @covers ::sourcetypeGet
     */
    public function testSourcetypeGet()
    {
        $this->markTestIncomplete(
            'Test of "sourcetypeGet" method has not been implemented yet.'
        );
    }

    /**
     * Test case for sourcetypeTypeIdGet
     *
     * Source type by id.
     *
     * @covers ::sourcetypeTypeIdGet
     */
    public function testSourcetypeTypeIdGet()
    {
        $this->markTestIncomplete(
            'Test of "sourcetypeTypeIdGet" method has not been implemented yet.'
        );
    }
}
