<?php

/**
 * Showcase API
 * PHP version 7.4
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for FHSTP Showcase
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace OpenAPIServer\Api;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Api\SessionApi;

/**
 * SessionApiTest Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Api\SessionApi
 */
class SessionApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getExamplesBySession
     *
     * Examples by session.
     *
     * @covers ::getExamplesBySession
     */
    public function testGetExamplesBySession()
    {
        $this->markTestIncomplete(
            'Test of "getExamplesBySession" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getSessionById
     *
     * Session by id.
     *
     * @covers ::getSessionById
     */
    public function testGetSessionById()
    {
        $this->markTestIncomplete(
            'Test of "getSessionById" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getSessionsByCourse
     *
     * Sessions by course.
     *
     * @covers ::getSessionsByCourse
     */
    public function testGetSessionsByCourse()
    {
        $this->markTestIncomplete(
            'Test of "getSessionsByCourse" method has not been implemented yet.'
        );
    }
}
