<?php

/**
 * Showcase API
 * PHP version 7.4
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for FHSTP Showcase
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace OpenAPIServer\Api;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Api\SourceApi;

/**
 * SourceApiTest Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Api\SourceApi
 */
class SourceApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getSourceById
     *
     * Source by id.
     *
     * @covers ::getSourceById
     */
    public function testGetSourceById()
    {
        $this->markTestIncomplete(
            'Test of "getSourceById" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getSourcesByExample
     *
     * Sources by example.
     *
     * @covers ::getSourcesByExample
     */
    public function testGetSourcesByExample()
    {
        $this->markTestIncomplete(
            'Test of "getSourcesByExample" method has not been implemented yet.'
        );
    }
}
