<?php

/**
 * Showcase API
 * PHP version 7.4
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for FHStP Showcase
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace OpenAPIServer\Api;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Api\StudyprogramApi;

/**
 * StudyprogramApiTest Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Api\StudyprogramApi
 */
class StudyprogramApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getStudyProgramById
     *
     * Study program by id.
     *
     * @covers ::getStudyProgramById
     */
    public function testGetStudyProgramById()
    {
        $this->markTestIncomplete(
            'Test of "getStudyProgramById" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getStudyPrograms
     *
     * All study programs.
     *
     * @covers ::getStudyPrograms
     */
    public function testGetStudyPrograms()
    {
        $this->markTestIncomplete(
            'Test of "getStudyPrograms" method has not been implemented yet.'
        );
    }
}
