<?php

/**
 * Showcase API
 * PHP version 7.4
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for FHStP Showcase
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\BaseModel;

/**
 * Course
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class Course extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\OpenAPIServer\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "title" : "Course",
  "required" : [ "id", "studyProgramId", "title" ],
  "type" : "object",
  "properties" : {
    "id" : {
      "type" : "integer",
      "description" : "The course id"
    },
    "title" : {
      "type" : "string",
      "description" : "The course title"
    },
    "subtitle" : {
      "type" : "string",
      "description" : "The course subtitle (optional)"
    },
    "studyProgramId" : {
      "type" : "integer",
      "description" : "The id of the study program the course belongs to"
    },
    "moodleUrl" : {
      "type" : "string",
      "description" : "The URL of the course in Moodle aka eCampus (optional)"
    }
  },
  "description" : "A course (LV) in a study program"
}
SCHEMA;
}
