<?php

/**
 * Showcase API
 * PHP version 7.4
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for FHStP Showcase
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\BaseModel;

/**
 * Example
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class Example extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\OpenAPIServer\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "title" : "Example",
  "required" : [ "id", "sessionId", "title" ],
  "type" : "object",
  "properties" : {
    "id" : {
      "type" : "integer",
      "description" : "The example id"
    },
    "sessionId" : {
      "type" : "integer",
      "description" : "The id of the session the example belongs to"
    },
    "title" : {
      "type" : "string",
      "description" : "The example title, e.g. 'Example 1', To-do List'"
    },
    "subtitle" : {
      "type" : "string",
      "description" : "The example subtitle (optional)"
    },
    "icon" : {
      "type" : "string",
      "description" : "The example icon (optional)"
    },
    "image" : {
      "type" : "string",
      "description" : "The example image (optional)"
    },
    "component" : {
      "type" : "string",
      "description" : "The name of the component showcasing the example, e.g. 'TodoList' (optional)"
    }
  },
  "description" : "A code example as demonstrated in a session"
}
SCHEMA;
}
