<?php

/**
 * Showcase API
 * PHP version 7.4
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for FHStP Showcase
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\BaseModel;

/**
 * Session
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class Session extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\OpenAPIServer\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "title" : "Session",
  "required" : [ "courseId", "id", "title" ],
  "type" : "object",
  "properties" : {
    "id" : {
      "type" : "integer",
      "description" : "The session id"
    },
    "courseId" : {
      "type" : "integer",
      "description" : "The id of the course the session belongs to"
    },
    "title" : {
      "type" : "string",
      "description" : "The session title, e.g. 'Lecture 1'"
    },
    "subtitle" : {
      "type" : "string",
      "description" : "The session subtitle (optional)"
    },
    "image" : {
      "type" : "string",
      "description" : "The session image (optional)"
    },
    "date" : {
      "type" : "string",
      "description" : "The date of the session (optional)"
    }
  },
  "description" : "A session (lecture or exercise) of a course"
}
SCHEMA;
}
