<?php

/**
 * Showcase API
 * PHP version 7.4
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for FHStP Showcase
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\BaseModel;

/**
 * SourceType
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class SourceType extends BaseModel
{
    /**
     * @var string Models namespace.
     * Can be required for data deserialization when model contains referenced schemas.
     */
    protected const MODELS_NAMESPACE = '\OpenAPIServer\Model';

    /**
     * @var string Constant with OAS schema of current class.
     * Should be overwritten by inherited class.
     */
    protected const MODEL_SCHEMA = <<<'SCHEMA'
{
  "title" : "SourceType",
  "required" : [ "id", "title" ],
  "type" : "object",
  "properties" : {
    "id" : {
      "type" : "integer",
      "description" : "The (internal) id of the source type"
    },
    "title" : {
      "type" : "string",
      "description" : "The title of the source type, e.g. 'Svelte', 'React', 'Vanilla', 'HTML', 'CSS', 'JavaScript'"
    },
    "icon" : {
      "type" : "string",
      "description" : "The icon of the source type (optional)"
    },
    "language" : {
      "type" : "string",
      "description" : "The language of the source type used for syntax highlighting (optional)"
    }
  },
  "description" : "A type (language/framework) of a source code"
}
SCHEMA;
}
