<?php

/**
 * Showcase API
 * PHP version 7.4
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * API for FHSTP Showcase
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace OpenAPIServer\Model;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Model\Example;

/**
 * ExampleTest Class Doc Comment
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Model\Example
 */
class ExampleTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Example"
     */
    public function testExample()
    {
        $testExample = new Example();
        $namespacedClassname = Example::getModelsNamespace() . '\\Example';
        $this->assertSame('\\' . Example::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        $this->markTestIncomplete(
            'Test of "Example" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        $this->markTestIncomplete(
            'Test of "id" property in "Example" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "sessionId"
     */
    public function testPropertySessionId()
    {
        $this->markTestIncomplete(
            'Test of "sessionId" property in "Example" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
        $this->markTestIncomplete(
            'Test of "title" property in "Example" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "subtitle"
     */
    public function testPropertySubtitle()
    {
        $this->markTestIncomplete(
            'Test of "subtitle" property in "Example" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "icon"
     */
    public function testPropertyIcon()
    {
        $this->markTestIncomplete(
            'Test of "icon" property in "Example" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "image"
     */
    public function testPropertyImage()
    {
        $this->markTestIncomplete(
            'Test of "image" property in "Example" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "component"
     */
    public function testPropertyComponent()
    {
        $this->markTestIncomplete(
            'Test of "component" property in "Example" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = Example::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}
